Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Max: 350

Metrics/MethodLength:
  Max: 100

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/StringConversionInInterpolation:
  Enabled: false
